// Generated by CoffeeScript 1.6.3
(function($) {
  $.fn.four04 = function(options) {
    var jqxhr, settings;
    settings = $.extend({
      color: "#FF6D00",
      backgroundColor: "white",
      bareCSS: "true",
      width: 500,
      wrapperClass: "kids404-wrapper",
      kidsId: "kids404",
      cssFile: "../src/embed-jquery.css",
      apiURL: "http://404kids.org/api/random",
      htmlTemplate: "<div class=\"{{wrapperClass}}\">\n  <div class=\"front\">\n    <h2>Missing Person Near <span class=\"geo-city\">Seattle</span></h2>\n    <div class=\"image\">\n      <img src=\"http://missingkids.com/{{image_url}}\">\n    </div>\n    <div class=\"info\">\n      <h3>{{full_name}}</h3>\n      <h4>Current Age {{ageString}}</h4>\n      <h4>Missing From {{missing_city}}, {{missing_state}}\n      <br>since {{month}} {{day}}, {{year}}</h4>\n      <h4 class=\"question\">Have You Seen This Person?</h4>\n      <br>\n      <a href=\"{{missingLink}}\" class=\"btn\">SEEN</a>\n      <a href=\"#\" onclick=\"showKid({{id}});return false;\" class=\"btn\">NO</a>\n    </div>\n    <div class=\"more-info\" onclick=\"document.getElementById('kids404').className = 'flipped';\">\n      <span>?</span>\n    </div>\n  </div>\n  <div class=\"back\">\n    <p>This service is brought to you by <a href=\"http://404kids.org\">404kids</a>, and is intended to help reclaim\n    the visibility and independence of missing children.</p>\n\n    <p>If you would like to aid in\n    the search for missing and exploited adolescents, please <a href=\"http://404kids.org/docs\">add this widget to your site</a>.</p>\n\n    <p>If you have any information to report on one of our featured subjects, we urge you to <a href=\"{{missingLink}}\">fill out a report</a> immediately.</p>\n    <div class=\"more-info\" onclick=\"document.getElementById('kids404').className = '';\">\n      <span>x</span>\n    </div>\n  </div>\n</div>"
    }, options);
    this.attr("id", "" + settings.kidsId);
    window.kidsCont = this;
    return jqxhr = $.getJSON(settings.apiURL, function(data) {
      var kid, months;
      kid = data.kid;
      months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
      console.log(kid.age);
      console.log(kid.missing_url);
      console.log(kid.id);
      return window.kidView = {
        wrapperClass: settings.wrapperClass,
        image_url: kid.image_url,
        full_name: kid.full_name,
        ageString: kid.age ? "" + kid.age + " Years Old" : "Age Not Provided",
        missing_city: kid.missing_city,
        missing_state: kid.missing_state,
        year: parseInt(kid.missing_date.slice(0, 4), 10),
        month: months[parseInt(kid.missing_date.slice(5, 7), 10)],
        day: parseInt(kid.missing_date.slice(8, 10), 10),
        missingLink: kid.missing_url,
        id: kid.id
      };
    }).done(function() {
      return window.kidsCont.html(Mustache.render(settings.htmlTemplate, window.kidView));
    }).error(function() {
      return console.log("error loading json data.");
    });
  };
  return this.showKid = function(exclude) {
    return console.log("public showKid triggered => " + exclude);
  };
})(jQuery);
